[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python -m alembic upgrade head"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[[envs]]
key = "ENVIRONMENT"
value = "production"
